var chart = AmCharts.makeChart("chartdiv", {
        "type": "serial",
        "theme": "dark",
        "pathToImages": "http://www.amcharts.com/lib/3/images/",
        "dataProvider": [{
            "year": "1980",
            "value": 20
        }, {
            "year": "1981",
            "value": 19
        }, {
            "year": "1982",
            "value": 21
        }, {
            "year": "1983",
            "value": 21
        }, {
            "year": "1984",
            "value": 22
        }, {
            "year": "1985",
            "value": 25
        }, {
            "year": "1986",
            "value": 30
        }, {
            "year": "1987",
            "value": 28
        }, {
            "year": "1988",
            "value": 28
        }, {
            "year": "1989",
            "value": 29
        }, {
            "year": "1990",
            "value": 29
        }, {
            "year": "1991",
            "value": 28
        }, {
            "year": "1992",
            "value": 27
        }, {
            "year": "1993",
            "value": 28
        }, {
            "year": "1994",
            "value": 29
        }, {
            "year": "1995",
            "value": 33
        }, {
            "year": "1996",
            "value": 35
        }, {
            "year": "1997",
            "value": 36
        }, {
            "year": "1998",
            "value": 31
        }, {
            "year": "1999",
            "value": 30
        }, {
            "year": "2000",
            "value": 29
        }, {
            "year": "2001",
            "value": 29
        }, {
            "year": "2002",
            "value": 31
        }, {
            "year": "2003",
            "value": 33
        }, {
            "year": "2004",
            "value": 33
        }, {
            "year": "2005",
            "value": 35
        }, {
            "year": "2006",
            "value": 36
        }, {
            "year": "2007",
            "value": 36
        }, {
            "year": "2008",
            "value": 37
        }, {
            "year": "2009",
            "value": 38
        }, {
            "year": "2010",
            "value": 41
        }, {
            "year": "2011",
            "value": 43
        }],
        "balloon": {
            "cornerRadius": 6
        },
        "valueAxes": [{
            "axisAlpha": 0
        }],
        "graphs": [{
            "balloonText": "[[category]]<br><b><span style='font-size:14px;'>[[value]] C</span></b>",
            "bullet": "round",
            "bulletSize": 6,
            "connect": false,
            "lineColor": "#b6d278",
            "lineThickness": 2,
            "negativeLineColor": "#487dac",
            "valueField": "value"
        }],
        "chartCursor": {
            "categoryBalloonDateFormat": "YYYY",
            "cursorAlpha": 0,
            "cursorPosition": "mouse",
            "graphBulletSize": 2
        },
        chartScrollbar:{},
        "dataDateFormat": "YYYY",
        "categoryField": "year",
        "categoryAxis": {
            "minPeriod": "YYYY",
            //"parseDates": true,
            //"minorGridEnabled": true
            "parseDates": false,
            "minorGridEnabled": false
        }
    }
);